import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Assistant, Secular_One } from "next/font/google";

const assistant = Assistant({
  subsets: ["latin", "hebrew"],
  variable: "--font-assistant",
});

const secularOne = Secular_One({
  subsets: ["latin", "hebrew"],
  weight: "400",
  variable: "--font-secular-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body
        className={`${assistant.variable} ${secularOne.variable} antialiased font-sans`}
        suppressHydrationWarning
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
